### ISSUE TITLE
Texture issues with some accessories

### ISSUE THREAD

**Issue by Than5562** [CiscuLog/Visual-Enchantments#1]
I found that some colors in these following items: Diamond Helmet, Diamond Leggings, Diamond Boots, Diamond Pickaxe, Diamond Axe, Diamond Shovel, Diamond Hoe don't match with the default Minecraft textures so can you fix it?

By the way can you implement some tweaks in Vanilla Tweaks (Consistent Helmets and Hoe Fix) to the pack and fix the Netherite Layer 1 texture (the pointless dots in the helmet and the missing texture in the chestplate)? (If you can or want to, lah)
![Screenshot_20230129_095221](https://user-images.githubusercontent.com/108618478/215301981-34fa779f-e5e0-4b11-b399-36b9837a6f88.png)
![Screenshot_20230129_095235](https://user-images.githubusercontent.com/108618478/215301985-a7deaacb-5916-427c-a875-036a9c5e4330.png)
![Screenshot_20230129_095512](https://user-images.githubusercontent.com/108618478/215301988-86e2e76d-cb05-4de9-a6d9-0a83b8d6558d.png)

**Comment by CiscuLog** [comment]
I can only compromise on the diamond tools.
The other suggestions either require big reworks of the pack or are banal.

**Comment by CiscuLog** [comment]
The diamond tool textures are already grabbed from the default pack. Therefore, this issue can be closed.
